[00:00:00] Build started
[00:00:00] git clone -q --branch=master https://github.com/Washi1337/OldRod.git C:\projects\oldrod
[00:00:02] git checkout -qf 56fc436807c46f94ffc1c790b9d8426dae7be047
[00:00:02] Running Install scripts
[00:00:02] git submodule update --init
[00:00:03] Submodule 'src/Rivers' (https://github.com/Washi1337/Rivers) registered for path 'deps/Rivers'
[00:00:04] Cloning into 'C:/projects/oldrod/deps/Rivers'...
[00:00:04] Submodule path 'deps/Rivers': checked out '28b83ebde83d50199c8bb97e1d1a3cacd2097ffd'
[00:00:05] nuget restore
[00:00:06] MSBuild auto-detection: using msbuild version '17.7.2.37605' from 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin'.
[00:00:14] Restoring packages for C:\projects\oldrod\src\OldRod\OldRod.csproj...
[00:00:14] Restoring packages for C:\projects\oldrod\src\OldRod.Pipeline\OldRod.Pipeline.csproj...
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/system.drawing.common/index.json
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies/index.json
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.dotnet/index.json
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 21ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/system.drawing.common/index.json 41ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies/index.json 45ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.3/newtonsoft.json.13.0.3.nupkg
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/system.drawing.common/6.0.0/system.drawing.common.6.0.0.nupkg
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies/1.0.3/microsoft.netframework.referenceassemblies.1.0.3.nupkg
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.3/newtonsoft.json.13.0.3.nupkg 13ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/system.drawing.common/6.0.0/system.drawing.common.6.0.0.nupkg 14ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies/1.0.3/microsoft.netframework.referenceassemblies.1.0.3.nupkg 14ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net461/index.json
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net471/index.json
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.dotnet/index.json 128ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.dotnet/5.4.0/asmresolver.dotnet.5.4.0.nupkg
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.systemevents/index.json
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.systemevents/index.json 19ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.systemevents/6.0.0/microsoft.win32.systemevents.6.0.0.nupkg
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net461/index.json 98ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net461/1.0.3/microsoft.netframework.referenceassemblies.net461.1.0.3.nupkg
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.systemevents/6.0.0/microsoft.win32.systemevents.6.0.0.nupkg 14ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net471/index.json 121ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net471/1.0.3/microsoft.netframework.referenceassemblies.net471.1.0.3.nupkg
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.dotnet/5.4.0/asmresolver.dotnet.5.4.0.nupkg 99ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net461/1.0.3/microsoft.netframework.referenceassemblies.net461.1.0.3.nupkg 71ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net471/1.0.3/microsoft.netframework.referenceassemblies.net471.1.0.3.nupkg 94ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.pe/index.json
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/system.text.json/index.json
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/system.text.json/index.json 27ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/system.text.json/6.0.8/system.text.json.6.0.8.nupkg
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/system.text.json/6.0.8/system.text.json.6.0.8.nupkg 13ms
[00:00:15]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.pe/index.json 70ms
[00:00:15]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.pe/5.4.0/asmresolver.pe.5.4.0.nupkg
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/microsoft.bcl.asyncinterfaces/index.json
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/microsoft.bcl.asyncinterfaces/index.json 18ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/microsoft.bcl.asyncinterfaces/6.0.0/microsoft.bcl.asyncinterfaces.6.0.0.nupkg
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json 18ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.6.0.0.nupkg
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/microsoft.bcl.asyncinterfaces/6.0.0/microsoft.bcl.asyncinterfaces.6.0.0.nupkg 13ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.pe/5.4.0/asmresolver.pe.5.4.0.nupkg 102ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.buffers/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.6.0.0.nupkg 12ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.memory/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.buffers/index.json 23ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.buffers/4.5.1/system.buffers.4.5.1.nupkg
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.buffers/4.5.1/system.buffers.4.5.1.nupkg 13ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/index.json 62ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.memory/index.json 44ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/6.0.0/system.text.encodings.web.6.0.0.nupkg
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.memory/4.5.4/system.memory.4.5.4.nupkg
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/6.0.0/system.text.encodings.web.6.0.0.nupkg 12ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.memory/4.5.4/system.memory.4.5.4.nupkg 13ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/index.json 47ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.pe.file/index.json
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.5.4/system.threading.tasks.extensions.4.5.4.nupkg
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.5.4/system.threading.tasks.extensions.4.5.4.nupkg 13ms
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.pe.file/index.json 82ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/asmresolver.pe.file/5.4.0/asmresolver.pe.file.5.4.0.nupkg
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/asmresolver.pe.file/5.4.0/asmresolver.pe.file.5.4.0.nupkg 88ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/asmresolver/index.json
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/asmresolver/index.json 72ms
[00:00:16]   GET https://api.nuget.org/v3-flatcontainer/asmresolver/5.4.0/asmresolver.5.4.0.nupkg
[00:00:16]   OK https://api.nuget.org/v3-flatcontainer/asmresolver/5.4.0/asmresolver.5.4.0.nupkg 122ms
[00:00:17] Installed AsmResolver.PE.File 5.4.0 from https://api.nuget.org/v3/index.json with content hash s+N8weZJJLZENcfyh2p+PJPu1FnRO6QPEqJA/pzYE6OA3vzffm4I0xtecVkTkwHHcnjrWzAa1hlyJdvJOf4x+A==.
[00:00:17] Installed AsmResolver 5.4.0 from https://api.nuget.org/v3/index.json with content hash A7gC4YbhAiTMULDYGgPnL0y94bb9K8Bngu8sed4Cxv84AM/pgxQWbQ4jbpMptvxAAadcgAN6kzcmUll9jZ3K2g==.
[00:00:17] Installed AsmResolver.PE 5.4.0 from https://api.nuget.org/v3/index.json with content hash ceYF9Qmh+MjoVn9XoGf/F4VPkhhTQq4OeQOTkpmAzWSSOopcjaMD9smf7qxZlNL9PVhswWBx7f+U/dciuzShjw==.
[00:00:17] Installed Microsoft.Bcl.AsyncInterfaces 6.0.0 from https://api.nuget.org/v3/index.json with content hash UcSjPsst+DfAdJGVDsu346FX0ci0ah+lw3WRtn18NUwEqRt70HaOQ7lI72vy3+1LxtqI3T5GWwV39rQSrCzAeg==.
[00:00:17] Installed System.Runtime.CompilerServices.Unsafe 6.0.0 from https://api.nuget.org/v3/index.json with content hash /iUeP3tq1S0XdNNoMz5C9twLSrM/TH+qElHkXWaPvuNOt+99G75NrV0OS2EqHx5wMN7popYjpc8oTjC1y16DLg==.
[00:00:17] Installed System.Memory 4.5.4 from https://api.nuget.org/v3/index.json with content hash 1MbJTHS1lZ4bS4FmsJjnuGJOu88ZzTT2rLvrhW7Ygic+pC0NWA+3hgAen0HRdsocuQXCkUTdFn9yHJJhsijDXw==.
[00:00:17] Installed System.Threading.Tasks.Extensions 4.5.4 from https://api.nuget.org/v3/index.json with content hash zteT+G8xuGu6mS+mzDzYXbzS7rd3K6Fjb9RiZlYlJPam2/hU7JCBZBVEcywNuR+oZ1ncTvc/cq0faRr3P01OVg==.
[00:00:17] Installed System.Buffers 4.5.1 from https://api.nuget.org/v3/index.json with content hash Rw7ijyl1qqRS0YQD/WycNst8hUUMgrMH4FCn1nNm27M4VxchZ1js3fVjQaANHO5f3sN4isvP4a+Met9Y4YomAg==.
[00:00:17] Installed System.Text.Encodings.Web 6.0.0 from https://api.nuget.org/v3/index.json with content hash Vg8eB5Tawm1IFqj4TVK1czJX89rhFxJo9ELqc/Eiq0eXy13RK00eubyU6TJE6y+GQXjyV5gSfiewDUZjQgSE0w==.
[00:00:17] Installed Newtonsoft.Json 13.0.3 from https://api.nuget.org/v3/index.json with content hash HrC5BXdl00IP9zeV+0Z848QWPAoCr9P3bDEZguI+gkLcBKAOxix/tLEAAHC+UvDNPv4a2d18lOReHMOagPa+zQ==.
[00:00:17] Installed Microsoft.NETFramework.ReferenceAssemblies 1.0.3 from https://api.nuget.org/v3/index.json with content hash vUc9Npcs14QsyOD01tnv/m8sQUnGTGOw1BCmKcv77LBJY7OxhJ+zJF7UD/sCL3lYNFuqmQEVlkfS4Quif6FyYg==.
[00:00:17] Installed System.Text.Json 6.0.8 from https://api.nuget.org/v3/index.json with content hash WhW6zPEgRZoo+c1NEvSSmrME4+LqXmW6tcsRFsEiSMeco+qZ9rpLs7tT53EIkE/s9GNTYS4/STQoaGiKDSWifQ==.
[00:00:17] Installed AsmResolver.DotNet 5.4.0 from https://api.nuget.org/v3/index.json with content hash kjD/zEep/J6QIznKp7Mzvw+NR0B9J58HdWR/s9dWjv40OiTAj4H0VJwTelXcI/qNCPqUC7dXBWFwhNTthXnUSw==.
[00:00:17] Installed System.Drawing.Common 6.0.0 from https://api.nuget.org/v3/index.json with content hash NfuoKUiP2nUWwKZN6twGqXioIe1zVD0RIj2t976A+czLHr2nY454RwwXs6JU9Htc6mwqL6Dn/nEL3dpVf2jOhg==.
[00:00:18] Installed Microsoft.Win32.SystemEvents 6.0.0 from https://api.nuget.org/v3/index.json with content hash hqTM5628jSsQiv+HGpiq3WKBl2c8v1KZfby2J6Pr7pEPlK9waPdgEO6b8A/+/xn/yZ9ulv8HuqK71ONy2tg67A==.
[00:00:18] Generating MSBuild file C:\projects\oldrod\src\OldRod.Pipeline\obj\OldRod.Pipeline.csproj.nuget.g.props.
[00:00:18] Generating MSBuild file C:\projects\oldrod\src\OldRod.Pipeline\obj\OldRod.Pipeline.csproj.nuget.g.targets.
[00:00:18] Writing assets file to disk. Path: C:\projects\oldrod\src\OldRod.Pipeline\obj\project.assets.json
[00:00:18] Restored C:\projects\oldrod\src\OldRod.Pipeline\OldRod.Pipeline.csproj (in 3.75 sec).
[00:00:18] Restoring packages for C:\projects\oldrod\src\OldRod.Core\OldRod.Core.csproj...
[00:00:18] Generating MSBuild file C:\projects\oldrod\src\OldRod.Core\obj\OldRod.Core.csproj.nuget.g.props.
[00:00:18] Generating MSBuild file C:\projects\oldrod\src\OldRod.Core\obj\OldRod.Core.csproj.nuget.g.targets.
[00:00:18] Writing assets file to disk. Path: C:\projects\oldrod\src\OldRod.Core\obj\project.assets.json
[00:00:18] Restored C:\projects\oldrod\src\OldRod.Core\OldRod.Core.csproj (in 5 ms).
[00:00:18] Restoring packages for C:\projects\oldrod\deps\Rivers\Rivers\Rivers.csproj...
[00:00:18] Generating MSBuild file C:\projects\oldrod\deps\Rivers\Rivers\obj\Rivers.csproj.nuget.g.props.
[00:00:18] Generating MSBuild file C:\projects\oldrod\deps\Rivers\Rivers\obj\Rivers.csproj.nuget.g.targets.
[00:00:18] Writing assets file to disk. Path: C:\projects\oldrod\deps\Rivers\Rivers\obj\project.assets.json
[00:00:18] Restored C:\projects\oldrod\deps\Rivers\Rivers\Rivers.csproj (in 4 ms).
[00:00:21] Installed Microsoft.NETFramework.ReferenceAssemblies.net471 1.0.3 from https://api.nuget.org/v3/index.json with content hash Kf3vusy+mwHzn+0osmJAMrZNG00/UkwywjwfFKLUWSYEXiIMD6SEMGP9bG3sH1B54IiydxAneLubS5/Ajjn/Tw==.
[00:00:21] Installed Microsoft.NETFramework.ReferenceAssemblies.net461 1.0.3 from https://api.nuget.org/v3/index.json with content hash AmOJZwCqnOCNp6PPcf9joyogScWLtwy0M1WkqfEQ0M9nYwyDD7EX9ZjscKS5iYnyvteX7kzSKFCKt9I9dXA6mA==.
[00:00:21] Generating MSBuild file C:\projects\oldrod\src\OldRod\obj\OldRod.csproj.nuget.g.props.
[00:00:21] Generating MSBuild file C:\projects\oldrod\src\OldRod\obj\OldRod.csproj.nuget.g.targets.
[00:00:21] Writing assets file to disk. Path: C:\projects\oldrod\src\OldRod\obj\project.assets.json
[00:00:21] Restored C:\projects\oldrod\src\OldRod\OldRod.csproj (in 6.74 sec).
[00:00:21] 
[00:00:21] NuGet Config files used:
[00:00:21]     C:\Users\appveyor\AppData\Roaming\NuGet\NuGet.Config
[00:00:21]     C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.FallbackLocation.config
[00:00:21]     C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
[00:00:21] 
[00:00:21] Feeds used:
[00:00:21]     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
[00:00:21]     C:\Program Files\dotnet\library-packs
[00:00:21]     https://api.nuget.org/v3/index.json
[00:00:21] 
[00:00:21] Installed:
[00:00:21]     11 package(s) to C:\projects\oldrod\src\OldRod.Pipeline\OldRod.Pipeline.csproj
[00:00:21]     11 package(s) to C:\projects\oldrod\src\OldRod.Core\OldRod.Core.csproj
[00:00:21]     17 package(s) to C:\projects\oldrod\src\OldRod\OldRod.csproj
[00:00:21] msbuild "C:\projects\oldrod\OldRod.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
[00:00:22] MSBuild version 17.7.2+d6990bcfa for .NET Framework
[00:00:22] 
[00:00:28]   Rivers -> C:\projects\oldrod\deps\Rivers\Rivers\bin\Release\netstandard2.0\Rivers.dll
[00:00:30] C:\projects\oldrod\src\OldRod.Core\Ast\IL\Pattern\ILExpressionStatementPattern.cs(31,36): warning CS0108: 'ILExpressionStatementPattern.Expression' hides inherited member 'ILAstPattern.Expression(ILExpressionPattern)'. Use the new keyword if hiding was intended. [C:\projects\oldrod\src\OldRod.Core\OldRod.Core.csproj]
[00:00:30]   OldRod.Core -> C:\projects\oldrod\src\OldRod.Core\bin\Release\netstandard2.0\OldRod.Core.dll
[00:00:31]   OldRod.Pipeline -> C:\projects\oldrod\src\OldRod.Pipeline\bin\Release\netstandard2.0\OldRod.Pipeline.dll
[00:00:31]   Rivers -> C:\projects\oldrod\deps\Rivers\Rivers\bin\Release\net471\Rivers.dll
[00:00:31]   OldRod -> C:\projects\oldrod\src\OldRod\bin\Release\net471\OldRod.exe
[00:00:32]   OldRod -> C:\projects\oldrod\src\OldRod\bin\Release\netcoreapp3.1\OldRod.dll
[00:00:33] Discovering tests...OK
[00:00:33] Collecting artifacts...
[00:00:33] Found artifact 'src\OldRod\bin\Release' matching 'src\OldRod\bin\Release' path
[00:00:33] Uploading artifacts...
[00:00:33] 
[00:00:34] [1/1] Release...Zipping to Release.zip
[00:00:34] [1/1] src\OldRod\bin\Release.zip (3,256,048 bytes)...3%
[00:00:34] [1/1] src\OldRod\bin\Release.zip (3,256,048 bytes)...100%
[00:00:35] Build success
